"""
AI Director — LTX Director Multi-Segment Engine
One-shot LONG video generation with NATIVE audio (dialogue + ambience) via the
WhatDreamsCost `LTXDirector` node: feed it N segments (reference image + rich
prompt + optional spoken line each) and LTX-2.3-dev generates one continuous
video where characters actually speak their lines, segments transition
smoothly (transition LoRA), audio is generated by the model itself.

Template: app/knowledge/workflows/ltx_director_multi.json (UI graph format,
2 chained LTXDirector nodes × 5 segments each + audio concat + final mux).
This module converts that UI graph (subgraphs, Set/Get nodes, Anything
Everywhere, Reroutes, bypasses) into API format, patches the segment data
from the project's scenes, and submits it through the existing ComfyUIClient.

Models used (all in ComfyUI/models):
  diffusion_models/ltx-2-3-22b-dev-Q4_K_M.gguf   (unsloth GGUF of LTX-2.3 dev)
  loras/ltx-2.3-22b-distilled-lora-384-1.1.safetensors  @0.5 (fast-distill)
  loras/ltx2.3-transition.safetensors            @0.7 (smooth segment joins)
  loras/ltx-2-19b-ic-lora-detailer.safetensors   @0.4 (upscale detail pass)
  vae/LTX23_video_vae_bf16 + LTX23_audio_vae_bf16 + taeltx2_3 (preview)
  text_encoders/gemma_3_12B_it_fp4_mixed + ltx-2.3_text_projection_bf16
  latent_upscale_models/ltx-2.3-spatial-upscaler-x2-1.1
"""
import copy
import json
import time
import shutil
import random
import logging
import subprocess
import urllib.request
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

TEMPLATE_PATH = Path(__file__).parent.parent / "knowledge" / "workflows" / "ltx_director_multi.json"

# widget names that are UI-side companions of a seed widget, never API inputs
_SEED_CONTROL_VALUES = {"fixed", "increment", "decrement", "randomize"}
# virtual/UI-only node types that never reach the API prompt
_VIRTUAL_TYPES = {"SetNode", "GetNode", "Anything Everywhere", "Reroute",
                  "MarkdownNote", "Note", "PrimitiveNode"}

# GGUF the template actually loads (usman's proven 720p config uses the
# distilled Q3_K_S — fast, ~25min for a 60s video)
DEV_GGUF_CANDIDATES = ["LTX-2.3-22B-distilled-1.1-Q3_K_S.gguf"]


def _pick_dev_gguf(models_dir) -> str:
    for c in DEV_GGUF_CANDIDATES:
        if (Path(models_dir) / "diffusion_models" / c).exists():
            return c
    return DEV_GGUF_CANDIDATES[0]


# ── UI-graph → API-prompt conversion ───────────────────────────────────────

class GraphConverter:
    """Converts a ComfyUI UI-format graph (with subgraphs, Set/Get nodes,
    'Anything Everywhere' broadcasts, reroutes and bypassed nodes) into the
    flat API prompt format {id: {class_type, inputs}}."""

    def __init__(self, graph: dict, object_info: dict):
        self.graph = graph
        self.object_info = object_info
        self.subgraph_defs = {
            s["id"]: s for s in (graph.get("definitions") or {}).get("subgraphs", [])
        }
        self.nodes: dict = {}      # flat_id -> node dict (expanded)
        self.links: dict = {}      # link_id -> (origin_flat_id, origin_slot)
        self._uid = 0

    def _next_id(self) -> str:
        self._uid += 1
        return f"n{self._uid}"

    # ── expansion ──────────────────────────────────────────────────────

    def convert(self) -> dict:
        self._expand(self.graph["nodes"], self.graph.get("links", []),
                     outer_input_map={}, link_ns="top")
        self._resolve_set_get()
        self._resolve_everywhere()
        return self._emit()

    def _expand(self, nodes: list, links: list, outer_input_map: dict,
                link_ns: str):
        """Flatten one graph level. outer_input_map maps this level's
        subgraph-input slot index -> (origin_flat_id, origin_slot) in the
        parent. Returns {output_slot_index: (flat_id, slot)} for -20 targets."""
        id_map = {}      # local node id -> flat id
        sub_instances = []
        for n in nodes:
            if n["type"] in self.subgraph_defs:
                sub_instances.append(n)
                continue
            fid = self._next_id()
            id_map[n["id"]] = fid
            self.nodes[fid] = copy.deepcopy(n)

        # normalize link records (top-level uses arrays, subgraphs use dicts)
        def rec(l):
            if isinstance(l, dict):
                return (l["id"], l["origin_id"], l["origin_slot"],
                        l["target_id"], l["target_slot"])
            return (l[0], l[1], l[2], l[3], l[4])

        out_map = {}
        pending_sub_links = []   # links touching a subgraph instance
        for l in links:
            lid, o_id, o_slot, t_id, t_slot = rec(l)
            key = f"{link_ns}:{lid}"
            if o_id == -10:                       # from subgraph input
                src = outer_input_map.get(o_slot)
                if src:
                    self.links[key] = src
            elif o_id in id_map:
                self.links[key] = (id_map[o_id], o_slot)
            else:
                pending_sub_links.append((lid, o_id, o_slot, t_id, t_slot))
            if t_id == -20 and key in self.links:  # to subgraph output
                out_map[t_slot] = self.links[key]

        # expand each subgraph instance
        for inst in sub_instances:
            sdef = self.subgraph_defs[inst["type"]]
            # 1. map DEF input slots -> parent link sources. Match by NAME:
            #    instances may omit inputs (e.g. an unlinked frame_rate), so
            #    positional mapping silently mis-wires everything after the gap.
            by_name = {}
            for iput in inst.get("inputs", []):
                l = iput.get("link")
                if l is not None:
                    src = self.links.get(f"{link_ns}:{l}")
                    if src:
                        by_name[iput["name"]] = src
            inst_in_map = {}
            for d_idx, d_input in enumerate(sdef.get("inputs", [])):
                src = by_name.get(d_input.get("name"))
                if src:
                    inst_in_map[d_idx] = src
            ns = f"{link_ns}/{inst['id']}"
            sub_out = self._expand(sdef["nodes"], sdef.get("links", []),
                                   inst_in_map, ns)
            # 2. instance output slot i -> inner source; register under the
            #    parent link ids attached to that output
            for idx, oput in enumerate(inst.get("outputs", [])):
                src = sub_out.get(idx)
                if not src:
                    continue
                for l in (oput.get("links") or []):
                    self.links[f"{link_ns}:{l}"] = src

        # unresolved forward references (source was a subgraph, now known)
        for lid, o_id, o_slot, t_id, t_slot in pending_sub_links:
            key = f"{link_ns}:{lid}"
            if key in self.links and t_id == -20:
                out_map[t_slot] = self.links[key]

        # record namespace on nodes for input resolution later
        for n_id, fid in id_map.items():
            self.nodes[fid]["_ns"] = link_ns
        return out_map

    # ── virtual node resolution ────────────────────────────────────────

    def _source_of(self, node: dict, input_index: int = 0):
        ns = node.get("_ns", "top")
        inputs = node.get("inputs", [])
        if input_index >= len(inputs):
            return None
        l = inputs[input_index].get("link")
        if l is None:
            return None
        return self.links.get(f"{ns}:{l}")

    def _resolve_set_get(self):
        """SetNode registers its input under a title; GetNode outputs it."""
        registry = self._registry = {}
        for fid, n in list(self.nodes.items()):
            if n["type"] == "SetNode":
                title = (n.get("widgets_values") or [n.get("title", "")])[0]
                src = self._source_of(n, 0)
                if src:
                    registry[str(title)] = src
        for fid, n in list(self.nodes.items()):
            if n["type"] == "GetNode":
                title = (n.get("widgets_values") or [n.get("title", "")])[0]
                src = registry.get(str(title))
                if not src:
                    continue
                ns = n.get("_ns", "top")
                for oput in n.get("outputs", []):
                    for l in (oput.get("links") or []):
                        self.links[f"{ns}:{l}"] = src

    def _resolve_everywhere(self):
        """'Anything Everywhere' broadcasts its input to every unlinked input
        of the same TYPE anywhere in the graph."""
        broadcasts = {}   # type -> (fid, slot)
        for fid, n in self.nodes.items():
            if n["type"].startswith("Anything Everywhere"):
                for idx, iput in enumerate(n.get("inputs", [])):
                    src = self._source_of(n, idx)
                    if src:
                        broadcasts[iput.get("type", "*")] = src
        if not broadcasts:
            return
        for fid, n in self.nodes.items():
            if n["type"] in _VIRTUAL_TYPES or n["type"].startswith("Anything Everywhere"):
                continue
            ns = n.get("_ns", "top")
            for iput in n.get("inputs", []):
                if iput.get("link") is None and iput.get("type") in broadcasts:
                    # synthesize a link
                    self._uid += 1
                    fake = f"ue{self._uid}"
                    iput["link"] = fake
                    self.links[f"{ns}:{fake}"] = broadcasts[iput["type"]]

    def _trace(self, src, want_type: Optional[str] = None, depth: int = 0):
        """Follow a (fid, slot) source through virtual/bypassed nodes until a
        real emitting node is reached."""
        if src is None or depth > 40:
            return None
        fid, slot = src
        n = self.nodes.get(fid)
        if n is None:
            return None
        ntype = n["type"]
        mode = n.get("mode", 0)
        if ntype == "Reroute":
            return self._trace(self._source_of(n, 0), want_type, depth + 1)
        if ntype == "GetNode":
            # GetNode has no inputs — resolve through the Set/Get registry
            title = (n.get("widgets_values") or [n.get("title", "")])[0]
            return self._trace(getattr(self, "_registry", {}).get(str(title)),
                               want_type, depth + 1)
        if ntype == "SetNode":
            return self._trace(self._source_of(n, 0), want_type, depth + 1)
        if mode in (2, 4):   # muted/bypassed: pass through matching input type
            out_type = None
            outs = n.get("outputs", [])
            if slot < len(outs):
                out_type = outs[slot].get("type")
            for idx, iput in enumerate(n.get("inputs", [])):
                if iput.get("type") == out_type or out_type in ("*", None):
                    nxt = self._source_of(n, idx)
                    if nxt:
                        return self._trace(nxt, want_type, depth + 1)
            return None
        return (fid, slot)

    # ── emission ───────────────────────────────────────────────────────

    def _widget_input_names(self, class_type: str) -> list:
        """Ordered input names that consume widgets_values entries."""
        info = self.object_info.get(class_type)
        if not info:
            return []
        names = []
        for section in ("required", "optional"):
            for name, spec in (info["input"].get(section) or {}).items():
                type_spec = spec[0] if isinstance(spec, list) and spec else spec
                opts = spec[1] if isinstance(spec, list) and len(spec) > 1 and isinstance(spec[1], dict) else {}
                is_widget = isinstance(type_spec, list) or (
                    isinstance(type_spec, str)
                    and type_spec in ("INT", "FLOAT", "STRING", "BOOLEAN", "COMBO"))
                if opts.get("forceInput"):
                    is_widget = False
                names.append((name, is_widget))
        return names

    def _emit(self) -> dict:
        prompt = {}
        for fid, n in self.nodes.items():
            ntype = n["type"]
            if ntype in _VIRTUAL_TYPES or ntype.startswith("Anything Everywhere") \
                    or ntype in self.subgraph_defs:
                continue
            if n.get("mode", 0) in (2, 4):
                continue
            api_inputs = {}
            ns_inputs = n.get("inputs", [])

            # linked inputs
            linked_names = set()
            for idx, iput in enumerate(ns_inputs):
                if iput.get("link") is None:
                    continue
                src = self._trace(self._source_of(n, idx))
                if src:
                    api_inputs[iput["name"]] = [src[0], src[1]]
                    linked_names.add(iput["name"])

            # widget inputs
            wv = n.get("widgets_values")
            if isinstance(wv, dict):
                for k, v in wv.items():
                    if k not in linked_names and not k.startswith("videopreview"):
                        api_inputs[k] = v
            elif isinstance(wv, list):
                names = self._widget_input_names(ntype)
                wi = 0
                for name, is_widget in names:
                    if not is_widget:
                        continue
                    if wi >= len(wv):
                        break
                    val = wv[wi]
                    wi += 1
                    if name not in linked_names:
                        api_inputs[name] = val
                    # skip UI-only seed-control companion value
                    if name in ("seed", "noise_seed") and wi < len(wv) \
                            and isinstance(wv[wi], str) \
                            and wv[wi] in _SEED_CONTROL_VALUES:
                        wi += 1
            prompt[fid] = {"class_type": ntype, "inputs": api_inputs}
        return prompt


# ── Service ────────────────────────────────────────────────────────────────

COMFYUI_INPUT = Path(r"C:\ComfyUI_windows_portable_nvidia_cu126\ComfyUI_windows_portable\ComfyUI\input")

# Extra LoRAs chained into the director's MODEL path (after the template's
# dynamic_fro09 + transition LoRAs) when present in the loras folder.
#
# 2026-07-22: EMPTIED to match usman's proven "usman created ltx.json" exactly.
# That reference workflow loads ONLY dynamic_fro09 @1.0 + transition @0.7 (+ the
# steps=24 override) and produces sharper output FASTER. The two extras below
# (CameraControls @0.7, Crisp_Enhance @0.5) merged extra weights at every one of
# the 24 sampling steps × every segment × every director — slower, and a
# different look than usman's clean stack. Re-add here ONLY if a project needs
# them; per-project LoRAs still flow through via the `extra_loras` argument.
EXTRA_LORAS: list[tuple[str, float]] = []

REQUIRED_MODELS = [
    ("loras", "ltx-2.3-22b-distilled-lora-dynamic_fro09_avg_rank_105_bf16.safetensors"),
    ("loras", "ltx2.3-transition.safetensors"),
    ("loras", "ltx-2-19b-ic-lora-detailer.safetensors"),
    ("vae", "LTX23_video_vae_bf16.safetensors"),
    ("vae", "LTX23_audio_vae_bf16.safetensors"),
    ("vae", "taeltx2_3.safetensors"),
    ("text_encoders", "gemma_3_12B_it_fp4_mixed.safetensors"),
    ("text_encoders", "ltx-2.3_text_projection_bf16.safetensors"),
    ("latent_upscale_models", "ltx-2.3-spatial-upscaler-x2-1.1.safetensors"),
]


class LTXDirectorService:
    """Multi-segment long-video generation with native audio/dialogue."""

    def __init__(self, model_manager, config):
        self.manager = model_manager
        self.config = config

    def check_models(self) -> list:
        """Missing model files, if any."""
        missing = []
        for sub, fname in REQUIRED_MODELS:
            if not (self.config.paths.models_dir / sub / fname).exists():
                missing.append(f"{sub}/{fname}")
        if not any((self.config.paths.models_dir / "diffusion_models" / c).exists()
                   for c in DEV_GGUF_CANDIDATES):
            missing.append(f"diffusion_models/{DEV_GGUF_CANDIDATES[0]}")
        return missing

    # ── segment building ───────────────────────────────────────────────

    @staticmethod
    def build_segments(segments: list[dict], fps: int = 24):
        """segments: [{prompt, dialogue?, image_path, seconds}] →
        (timeline_json, local_prompts, lengths_csv, guides_csv, total_frames)."""
        tl, prompts, lengths = [], [], []
        start = 0.0
        for i, seg in enumerate(segments):
            frames = max(24, int(round(float(seg["seconds"]) * fps)))
            text = seg["prompt"].strip()
            if seg.get("dialogue"):
                text += f"\n{seg['dialogue'].strip()}"
            fname = Path(seg["image_path"]).name
            tl.append({
                "id": f"aidir{i}{random.randint(1000, 9999)}",
                "start": start,
                "length": float(frames),
                "prompt": text,
                "type": "image",
                "imageFile": fname,
                "imageB64": f"/api/view?filename={fname}&type=input&subfolder=",
            })
            prompts.append(text)
            lengths.append(str(frames))
            start += frames
        timeline = json.dumps({"segments": tl, "audioSegments": []})
        guides = ",".join("1.00" for _ in segments)
        return timeline, " | ".join(prompts), ",".join(lengths), guides, int(start)

    # ── workflow assembly ──────────────────────────────────────────────

    def _inject_extra_loras(self, graph: dict, extra: list[tuple[str, float]]):
        """Chain additional LoraLoaderModelOnly nodes into the top-level MODEL
        path (between the template's last LoRA and the 'Anything Everywhere'
        MODEL broadcast), so every sampler downstream sees them."""
        loras_dir = self.config.paths.models_dir / "loras"
        extra = [(f, w) for f, w in extra if (loras_dir / f).exists()]
        if not extra:
            return
        # the AE node that broadcasts MODEL — its input link is the chain end
        ae = next((n for n in graph["nodes"]
                   if n["type"].startswith("Anything Everywhere")
                   and any(i.get("type") == "MODEL" and i.get("link") is not None
                           for i in n.get("inputs", []))), None)
        if ae is None:
            logger.warning("[LTXDirector] no MODEL broadcast node — extra LoRAs skipped")
            return
        ae_input = next(i for i in ae["inputs"]
                        if i.get("type") == "MODEL" and i.get("link") is not None)
        tail_link = ae_input["link"]
        links = graph["links"]
        rec = next(l for l in links if l[0] == tail_link)
        origin_id, origin_slot = rec[1], rec[2]
        origin_node = next(n for n in graph["nodes"] if n["id"] == origin_id)

        nid = graph.get("last_node_id", 0)
        lid = graph.get("last_link_id", 0)
        prev_id, prev_slot = origin_id, origin_slot
        for fname, weight in extra:
            nid += 1
            lid += 1
            # link from previous chain end into this new lora node
            if prev_id == origin_id:
                # rewire the origin's output away from the AE link
                out = origin_node["outputs"][origin_slot]
                out["links"] = [l for l in (out.get("links") or [])
                                if l != tail_link] + [lid]
            else:
                prev_node = next(n for n in graph["nodes"] if n["id"] == prev_id)
                prev_node["outputs"][0]["links"] = [lid]
            links.append([lid, prev_id, prev_slot, nid, 0, "MODEL"])
            graph["nodes"].append({
                "id": nid, "type": "LoraLoaderModelOnly", "pos": [0, 0],
                "size": [270, 82], "flags": {}, "order": 0, "mode": 0,
                "inputs": [{"name": "model", "type": "MODEL", "link": lid}],
                "outputs": [{"name": "MODEL", "type": "MODEL", "links": []}],
                "properties": {"Node name for S&R": "LoraLoaderModelOnly"},
                "widgets_values": [fname, weight],
            })
            logger.info(f"[LTXDirector] + LoRA {fname} @{weight}")
            prev_id, prev_slot = nid, 0
        # last new node feeds the AE broadcast via the original link id
        last_node = graph["nodes"][-1]
        last_node["outputs"][0]["links"] = [tail_link]
        rec[1], rec[2] = prev_id, 0
        graph["last_node_id"] = nid
        graph["last_link_id"] = lid

    def build_workflow(self, segments: list[dict], width: int = 1280,
                       height: int = 704, fps: int = 24,
                       style_prompt: str = "",
                       extra_loras: Optional[list] = None) -> dict:
        """Patch the template with real segments and convert to API format.
        Segments are split across the template's two chained LTXDirector
        nodes (first half / second half)."""
        graph = json.loads(TEMPLATE_PATH.read_text(encoding="utf-8"))

        # User has selected their available models directly in the template JSON,
        # so we bypass the dynamic model substitution that used to overwrite them.

        # chain in the motion/detail LoRAs (+ any per-project ones)
        self._inject_extra_loras(
            graph, EXTRA_LORAS + list(extra_loras or []))

        # Proven recipe (usman's 25-min 720p run): 5-6 segments x ~5-6s =
        # ~30s per director node, up to 2 directors per workflow.
        if len(segments) > 12:
            raise ValueError(
                f"LTX Director supports at most 12 scenes per video "
                f"(6 per director node) — this project has {len(segments)}. "
                f"Reduce the scene count or use the clip-by-clip engine.")

        director_nodes = [n for n in graph["nodes"] if n["type"] == "LTXDirector"]
        director_nodes.sort(key=lambda n: n["id"])
        if len(segments) <= 6:
            # SINGLE-DIRECTOR mode: everything fits one node. Remove the
            # second director + its sampler subgraph so ComfyUI never runs
            # them, and bypass the joiners so branch 1 passes straight through.
            parts = [segments]
            d2 = director_nodes[1]
            d2_links = {l for o in (d2.get("outputs") or [])
                        for l in (o.get("links") or [])}
            drop = {id(d2)}
            for n in graph["nodes"]:
                if any(i.get("link") in d2_links for i in (n.get("inputs") or [])):
                    drop.add(id(n))          # director 2's sampler subgraph
                elif n["type"] in ("ImageBatchMulti", "AudioConcatenate"):
                    n["mode"] = 4            # bypass: image_1/audio1 pass through
            graph["nodes"] = [n for n in graph["nodes"] if id(n) not in drop]
            director_nodes = director_nodes[:1]
        else:
            # split across the two chained director nodes
            half = (len(segments) + 1) // 2
            parts = [segments[:half], segments[half:]]
        for node, part in zip(director_nodes, parts):
            tl, prompts, lengths, guides, total = self.build_segments(part, fps)
            wv = node["widgets_values"]
            if style_prompt:
                wv[0] = style_prompt
            wv[1] = total                # duration_frames
            wv[2] = round(total / fps)   # duration_seconds
            wv[3] = tl                   # timeline_data
            wv[4] = prompts              # local_prompts
            wv[5] = lengths              # segment_lengths
            # guide_strength MUST have exactly one entry per segment — the
            # template ships 5; a mismatched count degrades generation badly
            wv[7] = guides
            wv[9] = fps                  # frame_rate
            # Do NOT overwrite width and height (wv[11], wv[12]) to preserve
            # the user's native template resolution (e.g. 720p instead of 704p)
            # which prevents "trash" generation quality.

        # unique output prefix
        for n in graph["nodes"]:
            if n["type"] == "VHS_VideoCombine":
                n["widgets_values"]["filename_prefix"] = \
                    f"aidir_ltxdir/{int(time.time())}"

        object_info = self._object_info()
        api = GraphConverter(graph, object_info).convert()
        return api

    def _object_info(self) -> dict:
        with urllib.request.urlopen("http://127.0.0.1:8188/object_info",
                                    timeout=30) as resp:
            return json.loads(resp.read())

    # ── orchestration ──────────────────────────────────────────────────

    def generate(self, segments: list[dict], output_path: str,
                 width: int = 1280, height: int = 704, fps: int = 24,
                 style_prompt: str = "", timeout: float = 14400,
                 extra_loras: Optional[list] = None) -> str:
        """Full run: stage images → build workflow → submit → collect video.
        `segments`: [{prompt, dialogue?, image_path, seconds}]."""
        from app.services.comfyui_client import ComfyUIClient

        missing = self.check_models()
        if missing:
            raise RuntimeError(f"LTX Director models missing: {missing}")

        client = ComfyUIClient()
        if not client.ensure_running():
            raise RuntimeError("ComfyUI is not running")

        # stage reference images into ComfyUI/input
        COMFYUI_INPUT.mkdir(parents=True, exist_ok=True)
        for seg in segments:
            src = Path(seg["image_path"])
            if not src.exists():
                raise FileNotFoundError(f"Segment image missing: {src}")
            dst = COMFYUI_INPUT / src.name
            if not dst.exists() or dst.stat().st_size != src.stat().st_size:
                shutil.copy2(src, dst)

        # everything else out of VRAM — this is the biggest job we run
        try:
            self.manager.unload()
        except Exception:
            pass
        client.free_vram()
        time.sleep(2)
        client.free_vram()

        wf = self.build_workflow(segments, width, height, fps, style_prompt,
                                 extra_loras=extra_loras)
        logger.info(f"[LTXDirector] Submitting {len(segments)} segments "
                    f"({sum(float(s['seconds']) for s in segments):.0f}s total) "
                    f"as {len(wf)} API nodes")
        prompt_id = client.submit(wf)
        history = client.wait_for_completion(prompt_id, timeout=timeout)
        return client.collect_output(history, output_path)

    def _generate_chunked(self, segments: list[dict], project_dir,
                          out_path: str, chunk_size: int = 5,
                          extra_loras: Optional[list] = None) -> str:
        """Long videos via MULTIPLE ComfyUI calls, then concat — the proven way
        to exceed one director's length while staying inside usman's ~6s-segment
        recipe. Runs ONE single-director LTX call per chunk of `chunk_size`
        segments (5 × ~5s ≈ 25s per call ≈ 600 frames, within usman's proven
        720), saves each to ltx_parts/part_XX.mp4 immediately, then ffmpeg-concats
        every part into one video. There is NO overall length cap — a 3-4 min
        video is just ~8-10 of these ~25s passes stitched together. Resumable at
        PART granularity: a crash/power cut only redoes the part mid-render;
        finished parts are skipped."""
        import os
        chunks = [segments[i:i + chunk_size]
                  for i in range(0, len(segments), chunk_size)]
        if len(chunks) > 1 and len(chunks[-1]) == 1:
            # a lone trailing segment renders poorly — fold it into the
            # previous chunk (7 segments splits 4+3 across the two directors)
            chunks[-2].extend(chunks.pop())

        parts_dir = Path(project_dir) / "ltx_parts"
        parts_dir.mkdir(parents=True, exist_ok=True)
        part_files = []
        for i, chunk in enumerate(chunks):
            part = parts_dir / f"part_{i:02d}.mp4"
            if part.exists() and part.stat().st_size > 100_000:
                logger.info(f"[LTXDirector] director {i + 1}/{len(chunks)} "
                            f"already rendered — resuming past it")
            else:
                secs = sum(float(s["seconds"]) for s in chunk)
                logger.info(f"[LTXDirector] director {i + 1}/{len(chunks)}: "
                            f"{len(chunk)} segments ({secs:.0f}s)")
                # render to a temp name and swap in atomically: a power cut
                # mid-copy must never leave a corrupt part_XX.mp4 behind that
                # a later resume would silently trust
                tmp = parts_dir / f"part_{i:02d}.tmp.mp4"
                if tmp.exists():
                    tmp.unlink()
                self.generate(chunk, str(tmp), extra_loras=extra_loras)
                os.replace(tmp, part)
            part_files.append(part)

        lst = parts_dir / "concat.txt"
        lst.write_text("".join(f"file '{p.as_posix()}'\n" for p in part_files),
                       encoding="utf-8")
        subprocess.run(
            [str(self.config.paths.ffmpeg_bin), "-y", "-f", "concat",
             "-safe", "0", "-i", str(lst), "-c", "copy", str(out_path)],
            check=True, capture_output=True)
        return str(out_path)

    def generate_for_project(self, project_id: str) -> str:
        """Build segments from the project's scenes (uses each scene's still
        image + prompt + narration line as spoken dialogue) and run."""
        from app.database import get_session, Project, Scene, SceneStatus

        session = get_session()
        try:
            project = session.query(Project).get(project_id)
            if not project:
                raise ValueError(f"Project {project_id} not found")
            scenes = session.query(Scene).filter(
                Scene.project_id == project_id
            ).order_by(Scene.scene_number).all()

            images_dir = self.config.paths.projects_dir / project_id / "images"
            from app.services import master_director
            guidance_plan = []
            segments = []
            for idx, s in enumerate(scenes):
                # reference still, in priority order: user-pinned still →
                # generation output/thumbnail → batch-phase still file
                notes = s.director_notes or {}
                img = None
                for cand in (notes.get("pinned_still"), notes.get("pinned_image")):
                    if cand and Path(cand).exists():
                        img = cand
                        break
                if not img:
                    for g in reversed(s.generations or []):
                        for cand in (g.output_path, g.thumbnail_path):
                            if cand and Path(cand).exists() and \
                                    Path(cand).suffix.lower() in (".png", ".jpg", ".jpeg", ".webp"):
                                img = cand
                                break
                        if img:
                            break
                if not img:
                    stills = sorted(images_dir.glob(f"scene_{s.scene_number:03d}_*.png"))
                    if stills:
                        img = str(stills[-1])
                if not img:
                    continue
                # Song projects: the song is the soundtrack — characters must
                # NOT speak the lyric lines; keep native ambience only.
                dialogue = ""
                if s.narration_text and \
                        getattr(project, "project_type", "song") != "song":
                    dialogue = f'The narrator says: "{s.narration_text.strip()}"'
                # Master-director guidance: reuse the guidance saved at scene
                # planning; older scenes without one get it here (and it is
                # saved back so resume sees the identical storyboard).
                guidance = notes.get("director_guidance")
                if not guidance:
                    guidance = master_director.guidance_for(
                        idx, len(scenes), str(notes.get("section") or "verse"),
                        project_id)
                    new_notes = dict(notes)
                    new_notes["director_guidance"] = guidance
                    s.director_notes = new_notes
                guidance_plan.append(guidance)
                segments.append({
                    "prompt": master_director.apply_cue(s.prompt, guidance),
                    "dialogue": dialogue,
                    "image_path": img,
                    "seconds": float(s.duration or 5.0),
                })
            session.commit()   # persist any newly assigned guidance
            try:
                master_director.save_plan(
                    self.config.paths.projects_dir / project_id, guidance_plan)
            except Exception as g_err:
                logger.warning(f"[LTXDirector] guidance save failed: {g_err}")
            if len(segments) < 2:
                raise ValueError(
                    "LTX Director needs at least 2 scenes with a still image "
                    "each (generate stills first, or pin images per scene)")

            # per-project LoRAs ride along in the director's model chain
            proj_loras = []
            ids = project.default_lora_ids or []
            weights = project.default_lora_weights or []
            for i, f in enumerate(ids):
                w = weights[i] if i < len(weights) else 0.7
                proj_loras.append((Path(f).name, float(w)))

            project_dir = self.config.paths.projects_dir / project_id
            out = str(project_dir / "ltx_director_render.mp4")
            if len(segments) <= 5:
                # short video — a single usman-proven director pass, no concat
                result = self.generate(segments, out, extra_loras=proj_loras)
            else:
                # LONGER video — split into ~25s usman-proven passes (one
                # ComfyUI call each), saved to ltx_parts/part_XX.mp4 as they
                # finish, then concatenated. This is how a 3-4 min video is
                # built: ~8-10 stitched passes. Resume skips finished parts.
                result = self._generate_chunked(segments, project_dir, out,
                                                extra_loras=proj_loras)
            project.output_path = result
            session.commit()
            return result
        finally:
            session.close()
